"""initial

Revision ID: 2df02ff4d715
Revises: 
Create Date: 2026-03-25 13:07:05.556796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2df02ff4d715'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('specialty', sa.String(length=100), nullable=True),
    sa.Column('clinic_name', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('referrals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ocean_referral_id', sa.String(length=100), nullable=True),
    sa.Column('patient_first_name', sa.String(length=100), nullable=False),
    sa.Column('patient_last_name', sa.String(length=100), nullable=False),
    sa.Column('patient_dob', sa.Date(), nullable=False),
    sa.Column('patient_phn', sa.String(length=20), nullable=True),
    sa.Column('referring_physician_name', sa.String(length=100), nullable=False),
    sa.Column('referring_clinic', sa.String(length=200), nullable=True),
    sa.Column('referring_physician_phone', sa.String(length=20), nullable=True),
    sa.Column('referring_physician_fax', sa.String(length=20), nullable=True),
    sa.Column('chief_complaint', sa.Text(), nullable=False),
    sa.Column('clinical_notes', sa.Text(), nullable=True),
    sa.Column('relevant_history', sa.Text(), nullable=True),
    sa.Column('current_medications', sa.Text(), nullable=True),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.Column('relevant_investigations', sa.Text(), nullable=True),
    sa.Column('specialist_id', sa.Integer(), nullable=True),
    sa.Column('specialty_requested', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('triaged_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['specialist_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_referrals_ocean_referral_id'), ['ocean_referral_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_referrals_received_at'), ['received_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_referrals_specialist_id'), ['specialist_id'], unique=False)

    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referral_id', sa.Integer(), nullable=False),
    sa.Column('specialist_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=30), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('recommended_workup', sa.Text(), nullable=True),
    sa.Column('redirect_to', sa.String(length=200), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('delivery_status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['referral_id'], ['referrals.id'], ),
    sa.ForeignKeyConstraint(['specialist_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referral_id')
    )
    op.create_table('triage_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referral_id', sa.Integer(), nullable=False),
    sa.Column('appropriateness_score', sa.Integer(), nullable=False),
    sa.Column('completeness_score', sa.Integer(), nullable=False),
    sa.Column('urgency_score', sa.Integer(), nullable=False),
    sa.Column('recommended_priority', sa.String(length=20), nullable=False),
    sa.Column('missing_information', sa.JSON(), nullable=True),
    sa.Column('triage_notes', sa.Text(), nullable=True),
    sa.Column('flags', sa.JSON(), nullable=True),
    sa.Column('triaged_at', sa.DateTime(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['referral_id'], ['referrals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referral_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('triage_results')
    op.drop_table('feedback')
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_referrals_specialist_id'))
        batch_op.drop_index(batch_op.f('ix_referrals_received_at'))
        batch_op.drop_index(batch_op.f('ix_referrals_ocean_referral_id'))

    op.drop_table('referrals')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
