"""add clinical_category missing_workup response_templates batch_actions

Revision ID: 55120190a039
Revises: 2df02ff4d715
Create Date: 2026-03-28 17:52:04.434713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55120190a039'
down_revision = '2df02ff4d715'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('response_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('template_type', sa.String(length=20), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category', 'template_type', 'created_by', name='uq_template_category_type_user')
    )
    with op.batch_alter_table('response_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_response_templates_category'), ['category'], unique=False)

    op.create_table('batch_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referral_ids', sa.JSON(), nullable=False),
    sa.Column('action_type', sa.String(length=20), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('executed_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['executed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['response_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batch_action_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_feedback_batch_action_id', 'batch_actions', ['batch_action_id'], ['id'])

    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clinical_category', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('missing_workup', sa.JSON(), nullable=True))
        batch_op.create_index(batch_op.f('ix_referrals_clinical_category'), ['clinical_category'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_referrals_clinical_category'))
        batch_op.drop_column('missing_workup')
        batch_op.drop_column('clinical_category')

    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_constraint('fk_feedback_batch_action_id', type_='foreignkey')
        batch_op.drop_column('batch_action_id')

    op.drop_table('batch_actions')
    with op.batch_alter_table('response_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_response_templates_category'))

    op.drop_table('response_templates')
    # ### end Alembic commands ###
