"""add multi-specialty models and FK columns

Revision ID: 93ccf2436904
Revises: 55120190a039
Create Date: 2026-03-28 22:33:37.196473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93ccf2436904'
down_revision = '55120190a039'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specialties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('clinical_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('specialty_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('priority_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['specialty_id'], ['specialties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('specialty_id', 'slug', name='uq_category_specialty_slug')
    )
    with op.batch_alter_table('clinical_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clinical_categories_specialty_id'), ['specialty_id'], unique=False)

    op.create_table('priority_keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('specialty_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=100), nullable=False),
    sa.Column('priority_level', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['specialty_id'], ['specialties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('priority_keywords', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_priority_keywords_specialty_id'), ['specialty_id'], unique=False)

    op.create_table('triage_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('specialty_id', sa.Integer(), nullable=False),
    sa.Column('config_key', sa.String(length=100), nullable=False),
    sa.Column('config_value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['specialty_id'], ['specialties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('specialty_id', 'config_key', name='uq_triage_config_specialty_key')
    )
    with op.batch_alter_table('triage_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_triage_configs_specialty_id'), ['specialty_id'], unique=False)

    op.create_table('category_keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=100), nullable=False),
    sa.Column('use_word_boundary', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['clinical_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('category_keywords', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_category_keywords_category_id'), ['category_id'], unique=False)

    op.create_table('pathway_guidance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('consider_before', sa.JSON(), nullable=True),
    sa.Column('refer_if', sa.Text(), nullable=True),
    sa.Column('additional_notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['clinical_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id')
    )
    op.create_table('workup_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['clinical_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workup_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workup_items_category_id'), ['category_id'], unique=False)

    op.create_table('workup_keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workup_item_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=100), nullable=False),
    sa.Column('use_word_boundary', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['workup_item_id'], ['workup_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workup_keywords', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workup_keywords_workup_item_id'), ['workup_item_id'], unique=False)

    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialty_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_referrals_specialty_id'), ['specialty_id'], unique=False)
        batch_op.create_foreign_key('fk_referrals_specialty_id', 'specialties', ['specialty_id'], ['id'])

    with op.batch_alter_table('response_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialty_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_response_templates_specialty_id'), ['specialty_id'], unique=False)
        batch_op.create_foreign_key('fk_response_templates_specialty_id', 'specialties', ['specialty_id'], ['id'])

    with op.batch_alter_table('triage_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialty_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('triage_config_version', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key('fk_triage_results_specialty_id', 'specialties', ['specialty_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialty_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_specialty_id'), ['specialty_id'], unique=False)
        batch_op.create_foreign_key('fk_users_specialty_id', 'specialties', ['specialty_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_specialty_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_users_specialty_id'))
        batch_op.drop_column('specialty_id')

    with op.batch_alter_table('triage_results', schema=None) as batch_op:
        batch_op.drop_constraint('fk_triage_results_specialty_id', type_='foreignkey')
        batch_op.drop_column('triage_config_version')
        batch_op.drop_column('specialty_id')

    with op.batch_alter_table('response_templates', schema=None) as batch_op:
        batch_op.drop_constraint('fk_response_templates_specialty_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_response_templates_specialty_id'))
        batch_op.drop_column('specialty_id')

    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.drop_constraint('fk_referrals_specialty_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_referrals_specialty_id'))
        batch_op.drop_column('specialty_id')

    with op.batch_alter_table('workup_keywords', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workup_keywords_workup_item_id'))

    op.drop_table('workup_keywords')
    with op.batch_alter_table('workup_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workup_items_category_id'))

    op.drop_table('workup_items')
    op.drop_table('pathway_guidance')
    with op.batch_alter_table('category_keywords', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_keywords_category_id'))

    op.drop_table('category_keywords')
    with op.batch_alter_table('triage_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_triage_configs_specialty_id'))

    op.drop_table('triage_configs')
    with op.batch_alter_table('priority_keywords', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_priority_keywords_specialty_id'))

    op.drop_table('priority_keywords')
    with op.batch_alter_table('clinical_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clinical_categories_specialty_id'))

    op.drop_table('clinical_categories')
    op.drop_table('specialties')
    # ### end Alembic commands ###
