"""add patient_sex attachments referring_physician_specialty

Revision ID: e836ed2c1373
Revises: f6f7dc908151
Create Date: 2026-04-03 20:17:10.343724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e836ed2c1373'
down_revision = 'f6f7dc908151'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clinic_memberships', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_sex', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('referring_physician_specialty', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('attachments', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.drop_column('attachments')
        batch_op.drop_column('referring_physician_specialty')
        batch_op.drop_column('patient_sex')

    with op.batch_alter_table('clinic_memberships', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
