"""add clinic and clinic_membership models

Revision ID: f6f7dc908151
Revises: 93ccf2436904
Create Date: 2026-03-29 20:03:59.605927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6f7dc908151'
down_revision = '93ccf2436904'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('specialty_id', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('fax', sa.String(length=20), nullable=True),
    sa.Column('ocean_md_api_key', sa.String(length=500), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('subscription_tier', sa.String(length=20), nullable=True),
    sa.Column('subscription_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['specialty_id'], ['specialties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('clinics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clinics_specialty_id'), ['specialty_id'], unique=False)

    op.create_table('clinic_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('invite_token', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_token'),
    sa.UniqueConstraint('user_id', 'clinic_id', name='uq_user_clinic')
    )
    with op.batch_alter_table('clinic_memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clinic_memberships_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinic_memberships_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clinic_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('assigned_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_referrals_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_foreign_key('fk_referrals_clinic_id', 'clinics', ['clinic_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.drop_constraint('fk_referrals_clinic_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_referrals_clinic_id'))
        batch_op.drop_column('assigned_at')
        batch_op.drop_column('clinic_id')

    with op.batch_alter_table('clinic_memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clinic_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_clinic_memberships_clinic_id'))

    op.drop_table('clinic_memberships')
    with op.batch_alter_table('clinics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clinics_specialty_id'))

    op.drop_table('clinics')
    # ### end Alembic commands ###
